spring.application.name=taskmanager

# MongoDB Connection
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=taskmanager_dev

# Server Port
server.port=8080